const Joi = require('joi');

const cryRecordingValidationSchema = Joi.object({
  recording_id: Joi.number().integer().optional(), // Optional, auto-generated by Sequelize
  file_path: Joi.string()
    .pattern(/^(\/[a-zA-Z0-9_-]+)+\.[a-zA-Z0-9]+$/) // Simple pattern to validate file paths
    .max(500) // Maximum length of 500 characters
    .required(),

  prediction: Joi.string().optional(),

  file_format: Joi.string()
    .valid('mp3', 'wav', 'aac', 'flac') 
    .required(),

  baby_id: Joi.number().integer().required(), // Foreign key to Baby
});

module.exports = cryRecordingValidationSchema;
