const Joi = require('joi');

const languageValidationSchema = Joi.object({
  language_id: Joi.number().integer().optional(), // Auto-generated by Sequelize
  name: Joi.string().max(50).required(), 
  code: Joi.string().valid('en', 'ar').default('en').required(), // Language code, e.g., 'en', 'ar'
  direction: Joi.string().valid('LTR', 'RTL').default('LTR').required(), // Must be 'LTR' or 'RTL'
  is_active: Joi.boolean().default(true), // Default value is true
});

module.exports = languageValidationSchema;
